[[entries]]
title = "OpenMW"
launch_command = "/opt/openmw/openmw"
path_box_art = "/opt/openmw/openmw.png"
path_game_gir = "/opt/openmw"

[[entries]]
title = "OpenMW Launcher"
launch_command = "/opt/openmw/openmw-launcher"
path_box_art = "/opt/openmw/openmw.png"
path_game_gir = "/opt/openmw"

[[entries]]
title = "OpenMW CS"
launch_command = "/opt/openmw/openmw-cs"
path_box_art = "/opt/openmw/openmw.png"
path_game_gir = "/opt/openmw"
