# BEGIN_KITTY_THEME
# Rosé Pine Moon
include current-theme.conf
# END_KITTY_THEME
font_size           10.0
font_family         JetBrainsMono Nerd Font
bold_font           JetBrainsMono Nerd Font Bold
italic_font         JetBrainsMono Nerd Font Italic
bold_italic_font    JetBrainsMono Nerd Font Bold Italic

background_opacity  0.9
